.TH "/devel/graphdata/graphDataLib/src Directory Reference" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/devel/graphdata/graphDataLib/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBimpl\fP"
.br
.ti -1c
.RI "directory \fButil\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgraphInit\&.c\fP"
.br
.in -1c
