.TH "dimensions_t" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dimensions_t \- Structure to hold values for dimensional graphs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphData\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBdimcount\fP"
.br
.ti -1c
.RI "size_t * \fBdimarr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to hold values for dimensional graphs\&. 

This structure holds values defining the boundaries of a dimensional graph, such as one representing a spatial domain\&. 
.SH "Field Documentation"
.PP 
.SS "size_t* dimensions_t::dimarr"
Array pointer containing the upper dimensional boundary values (width, height, depth, etc)\&. 
.SS "size_t dimensions_t::dimcount"
Number of dimensions represented\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
