.TH "edge_t" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edge_t \- Graph edge structure, representing linkages between nodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphData\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBu\fP"
.br
.ti -1c
.RI "size_t \fBv\fP"
.br
.ti -1c
.RI "double \fBcap\fP"
.br
.ti -1c
.RI "double \fBflow\fP"
.br
.ti -1c
.RI "struct \fBfeature_t\fP * \fBattrs\fP"
.br
.ti -1c
.RI "struct \fBedge_t\fP * \fBprev\fP"
.br
.RI "Previous edge in the list\&. "
.ti -1c
.RI "struct \fBedge_t\fP * \fBnext\fP"
.br
.RI "Next edge in the list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Graph edge structure, representing linkages between nodes\&. 

The interpretation of an edge (path, traversal, relationship, association) is usage-dependent\&. In general, this structure contains enough information to carry out typical graph operations and algorithms\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBfeature_t\fP* edge_t::attrs"
Features associated with the edge\&. 
.SS "double edge_t::cap"
Baseline capacity or cost value\&. 
.SS "double edge_t::flow"
Additional flow (change in capacity value) for the edge\&. 
.SS "struct \fBedge_t\fP* edge_t::next"

.PP
Next edge in the list\&. Typical usage would be either for normal adjacency lists, or for edge-based path values\&. 
.SS "struct \fBedge_t\fP* edge_t::prev"

.PP
Previous edge in the list\&. Typical usage would be either for normal edge lists, or for edge-based path values\&. 
.SS "size_t edge_t::u"
Starting node 
.SS "size_t edge_t::v"
Ending node 

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
