.TH "feature_t" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
feature_t \- Feature/attribute structure for a graph item\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphData\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBhashid\fP"
.br
.RI "identifier for the feature type "
.ti -1c
.RI "char * \fBfeaturename\fP"
.br
.RI "text name of the feature type\&. "
.ti -1c
.RI "double \fBval\fP"
.br
.ti -1c
.RI "void * \fBfdata\fP"
.br
.ti -1c
.RI "struct \fBfeature_t\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBfeature_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Feature/attribute structure for a graph item\&. 

Features hold attribute values for the associated graph structure member (node, edge)\&. This structure can be used to store additional information or computation results\&. 
.SH "Field Documentation"
.PP 
.SS "void* feature_t::fdata"
Associated feature data\&. 
.SS "char* feature_t::featurename"

.PP
text name of the feature type\&. 
.SS "size_t feature_t::hashid"

.PP
identifier for the feature type Feature identifier, unique for a feature type\&. Basic concept is a hash of the feature name, though other implementations are possible\&. 
.SS "struct \fBfeature_t\fP* feature_t::next"
Next feature in the list\&. 
.SS "struct \fBfeature_t\fP* feature_t::prev"
Previous feature in the list\&. 
.SS "double feature_t::val"
Value of the feature\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
