.TH "/devel/graphdata/graphDataLib/include/impl/hashgraph.h" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/devel/graphdata/graphDataLib/include/impl/hashgraph.h
.SH SYNOPSIS
.br
.PP
\fC#include <graphData\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBhashGraphInit\fP (struct \fBgraph_t\fP *g)"
.br
.RI "Initialize the graph using the hashtable adjacency list structure\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int hashGraphInit (struct \fBgraph_t\fP * g)"

.PP
Initialize the graph using the hashtable adjacency list structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIg\fP Graph structure to be operated upon\&. 
.RE
.PP
\fBReturns\fP
.RS 4
1 if successful; 0 of there was a problem\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
