.TH "/devel/graphdata/graphDataLib/include/impl/linkops.h" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/devel/graphdata/graphDataLib/include/impl/linkops.h
.SH SYNOPSIS
.br
.PP
\fC#include <graphData\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBlinkNodeCount\fP (struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer definition for getting the node count;\&. "
.ti -1c
.RI "size_t \fBlinkEdgeCount\fP (struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to extract count of edges\&. "
.ti -1c
.RI "struct \fBnode_t\fP * \fBlinkGetNode\fP (const size_t *nodeid, const struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to retrieve a node structure reference\&. "
.ti -1c
.RI "struct \fBedge_t\fP * \fBlinkGetEdge\fP (const size_t *u, const size_t *v, const struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to retrieve a edge structure reference\&. "
.ti -1c
.RI "struct \fBnode_t\fP * \fBlinkGetNeighbors\fP (const size_t *nodeid, const struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to retrieve linked-list of nodes that are currently defined as neighbors to the given node\&. "
.ti -1c
.RI "struct \fBedge_t\fP * \fBlinkGetEdges\fP (const size_t *nodeid, const struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to retrieve linked-list of edges from a given node\&. Returned linked-list is distinct from the graph structure, and consumers must use free() when finished\&. "
.ti -1c
.RI "int \fBlinkGetCapacity\fP (const size_t *uid, const size_t *vid, double *cap, const struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to retrieve the current capacity value for a given edge\&. "
.ti -1c
.RI "int \fBlinkGetFlow\fP (const size_t *uid, const size_t *vid, double *flow, const struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to retrieve the current flow value for a given edge\&. "
.ti -1c
.RI "int \fBlinkAddNode\fP (const size_t *nodeid, struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to add a node to a given graph\&. Not all implementations may use this (for example, fixed-size graphs such as spatial ARRAY implementations)\&. "
.ti -1c
.RI "int \fBlinkRemoveNode\fP (const size_t *nodeid, struct \fBgraph_t\fP *g)"
.br
.RI "Remove a node from the graph\&. "
.ti -1c
.RI "int \fBlinkAddEdge\fP (const size_t *uid, const size_t *vid, double *cap, struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to add an edge to a given graph\&. Not all implementations may use this (for example, fixed-size ARRAY implementations representing a set domain of nodes and relationships)\&. "
.ti -1c
.RI "int \fBlinkRemoveEdge\fP (const size_t *uid, const size_t *vid, struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to remove an edge from the given graph\&. "
.ti -1c
.RI "int \fBlinkSetCapacity\fP (const size_t *uid, const size_t *vid, const double *cap, struct \fBgraph_t\fP *g)"
.br
.RI "Function pointer to set the capacity (cost, weight, etc\&.) of an edge in the given graph\&. "
.ti -1c
.RI "int \fBlinkAddCapacity\fP (const size_t *uid, const size_t *vid, const double *cap, struct \fBgraph_t\fP *g)"
.br
.RI "Function to add (adjust) the capacity for an edge by a given amount\&. "
.ti -1c
.RI "int \fBlinkSetFlow\fP (const size_t *uid, const size_t *vid, const double *flow, struct \fBgraph_t\fP *g)"
.br
.RI "Function to set the flow value for an edge (amount of capacity currently 'used') "
.ti -1c
.RI "int \fBlinkAddFlow\fP (const size_t *uid, const size_t *vid, const double *flow, struct \fBgraph_t\fP *g)"
.br
.RI "Function to adjust the flow value of a given edge\&. "
.ti -1c
.RI "int \fBlinkResetGraph\fP (struct \fBgraph_t\fP *g, void *args, void(*callback)(void))"
.br
.RI "Function pointer to 'reset' the graph according to the given argument pointer\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int linkAddCapacity (const size_t * uid, const size_t * vid, const double * cap, struct \fBgraph_t\fP * g)"

.PP
Function to add (adjust) the capacity for an edge by a given amount\&. For implementations that require it, this function allows the altering of a specified edge capacity by the given amount\&.
.PP
\fBParameters\fP
.RS 4
\fIuid\fP Identifier of the edge start 
.br
\fIvid\fP Identifier of the edge end\&. 
.br
\fIcap\fP Value to adjust the capacity 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error (edge not found, for example); 1 of capacity was successfully adjusted 
.RE
.PP

.SS "int linkAddEdge (const size_t * uid, const size_t * vid, double * cap, struct \fBgraph_t\fP * g)"

.PP
Function pointer to add an edge to a given graph\&. Not all implementations may use this (for example, fixed-size ARRAY implementations representing a set domain of nodes and relationships)\&. 
.PP
\fBParameters\fP
.RS 4
\fIuid\fP identifer for start of edge 
.br
\fIvid\fP identifier for end of edge 
.br
\fIcap\fP capacity value to be assigned 
.br
\fIg\fP graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error; 1 if the edge was successfully added\&.
.RE
.PP
Function pointer to add an edge to a given graph\&. Not all implementations may use this (for example, fixed-size ARRAY implementations representing a set domain of nodes and relationships)\&.
.PP
Remove the node and repair the linked list, as necessary
.PP
\fBParameters\fP
.RS 4
\fIuid\fP identifer for start of edge 
.br
\fIvid\fP identifier for end of edge 
.br
\fIcap\fP capacity value to be assigned 
.br
\fIg\fP graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error; 1 if the edge was successfully added\&. 
.RE
.PP

.SS "int linkAddFlow (const size_t * uid, const size_t * vid, const double * flow, struct \fBgraph_t\fP * g)"

.PP
Function to adjust the flow value of a given edge\&. For implementations that require it, this allows ajustment of the amount of capacity that is being 'used'\&.
.PP
\fBParameters\fP
.RS 4
\fIuid\fP Identifier of the edge start 
.br
\fIvid\fP Identifier of the edge end\&. 
.br
\fIflow\fP The value to be added to adjust the flow value\&. 
.br
\fIg\fP The graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error (such as the edge not found); otherwise, 1 if the flow value was successfully adjusted\&. 
.RE
.PP

.SS "int linkAddNode (const size_t * nodeid, struct \fBgraph_t\fP * g)"

.PP
Function pointer to add a node to a given graph\&. Not all implementations may use this (for example, fixed-size graphs such as spatial ARRAY implementations)\&. 
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Node identifier to be added 
.br
\fIg\fP Graph structure to add the node 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error, 1 if the node was successfully added
.RE
.PP
Function pointer to add a node to a given graph\&. Not all implementations may use this (for example, fixed-size graphs such as spatial ARRAY implementations)\&.
.PP
Add a new node to the end of the node list
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Node identifier to be added 
.br
\fIg\fP Graph structure to add the node 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error, 1 if the node was successfully added 
.RE
.PP

.SS "size_t linkEdgeCount (struct \fBgraph_t\fP * g)"

.PP
Function pointer to extract count of edges\&. 
.PP
\fBParameters\fP
.RS 4
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
Count of edges, if graph is not null; otherwise, return 0 
.RE
.PP

.SS "int linkGetCapacity (const size_t * uid, const size_t * vid, double * cap, const struct \fBgraph_t\fP * g)"

.PP
Function pointer to retrieve the current capacity value for a given edge\&. For implementations that support this, the capacity value will be written to the *cap parameter\&.
.PP
\fBParameters\fP
.RS 4
\fIuid\fP Edge start identifier 
.br
\fIvid\fP Edge end identifier 
.br
\fIcap\fP Capacity value pointer to store the value 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was a problem retrieving the value (such as the edge not existing); otherwise, 1 for a successful retrieval 
.RE
.PP

.SS "struct \fBedge_t\fP * linkGetEdge (const size_t * u, const size_t * v, const struct \fBgraph_t\fP * g)"

.PP
Function pointer to retrieve a edge structure reference\&. Implementation-specific on whether this structure is part of the original graph (LINK-based implementations) or must use free() when usage is finished (ARRAY-based)\&. 
.PP
\fBParameters\fP
.RS 4
\fIu\fP nodeid of the starting edge\&. 
.br
\fIv\fP nodeid of the ending edge\&. 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the edge structure, if found; otherwise, pointer to NULL\&.
.RE
.PP
Walks the structure to find the given edge
.PP
\fBParameters\fP
.RS 4
\fIu\fP nodeid of the starting edge\&. 
.br
\fIv\fP nodeid of the ending edge\&. 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the edge structure, if found; otherwise, pointer to NULL\&. 
.RE
.PP

.SS "struct \fBedge_t\fP * linkGetEdges (const size_t * nodeid, const struct \fBgraph_t\fP * g)"

.PP
Function pointer to retrieve linked-list of edges from a given node\&. Returned linked-list is distinct from the graph structure, and consumers must use free() when finished\&. 
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Identifier of the node in question 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
linked-list of edges starting from the given node, if found; otherwise, pointer to NULL\&.
.RE
.PP
Function pointer to retrieve linked-list of edges from a given node\&. Returned linked-list is distinct from the graph structure, and consumers must use free() when finished\&.
.PP
Returned linked-list is distinct from the graph structure, and consumers must use free() when finished\&.
.PP
The edges returned are outgoing edges in the case of a DIRECTED graph\&.
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Identifier of the node in question 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
linked-list of edges starting from the given node, if found; otherwise, pointer to NULL\&. 
.RE
.PP

.SS "int linkGetFlow (const size_t * uid, const size_t * vid, double * flow, const struct \fBgraph_t\fP * g)"

.PP
Function pointer to retrieve the current flow value for a given edge\&. For implementations that support this, the flow value will be written to the *flow parameter\&.
.PP
\fBParameters\fP
.RS 4
\fIuid\fP Edge start identifier 
.br
\fIvid\fP Edge end identifier 
.br
\fIflow\fP Flow value pointer to store the result 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was a problem retrieving the value (such as the edge not existing); otherwise, 1 for a successful retrieval 
.RE
.PP

.SS "struct \fBnode_t\fP * linkGetNeighbors (const size_t * nodeid, const struct \fBgraph_t\fP * g)"

.PP
Function pointer to retrieve linked-list of nodes that are currently defined as neighbors to the given node\&. Returned linked-list is distinct from the graph structure, and consumers must use free() when finished\&. 
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Identifier of the node in question 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
linked-list of node references, starting with the given node, if found; otherwise, pointer to NULL\&.
.RE
.PP
Returned linked-list is distinct from the graph structure, and consumers must use free() when finished\&. The edges returned are outgoing neighbors (in the case of a DIRECTED graph)\&.
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Identifier of the node in question 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
linked-list of node references, starting with the given node, if found; otherwise, pointer to NULL\&. 
.RE
.PP

.SS "struct \fBnode_t\fP * linkGetNode (const size_t * nodeid, const struct \fBgraph_t\fP * g)"

.PP
Function pointer to retrieve a node structure reference\&. Implementation-specific on whether this structure is part of the original graph (LINK-based implementations) or must use free() when usage is finished (ARRAY-based)\&. 
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Identifier of the node to be retrieved 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
pointer to the node structure, if found; otherwise, pointer to NULL 
.RE
.PP

.SS "size_t linkNodeCount (struct \fBgraph_t\fP * g)"

.PP
Function pointer definition for getting the node count;\&. 
.PP
\fBParameters\fP
.RS 4
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
Count of nodes, if graph is not null; otherwise, return 0
.RE
.PP
Function pointer definition for getting the node count;\&.
.PP
This implementation is for a linked-list graph structure that uses the minimum necessary memory to store vertex and edge data for a graph\&. The intent is to support the most general graph usage, wherein the user of the graph structure may not be able to determine exact relationship before graph creation\&.
.PP
In this first version, the operations are implemented around a double-linked list structure, with node and edge walking as necessary to find the appropriate relationships\&. Future versions will attempt to add more nuanced and intelligent layouts in order to speed up operations\&.
.PP
Function pointer definition for getting the node count
.PP
Walks the node structure to find the total number of nodes in the graph 
.PP
\fBParameters\fP
.RS 4
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
Count of nodes, if graph is not null; otherwise, return 0 
.RE
.PP

.SS "int linkRemoveEdge (const size_t * uid, const size_t * vid, struct \fBgraph_t\fP * g)"

.PP
Function pointer to remove an edge from the given graph\&. Allows implementations to remove a given edge from the graph, if necessary\&.
.PP
\fBParameters\fP
.RS 4
\fIuid\fP Identifier for the edge start 
.br
\fIvid\fP Identifier for the edge end\&. 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error (e\&.g\&. the edge was not found); otherwise, 1 if the edge was removed\&. 
.RE
.PP

.SS "int linkRemoveNode (const size_t * nodeid, struct \fBgraph_t\fP * g)"

.PP
Remove a node from the graph\&. Not all implementations will allow removal of nodes\&. 
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Node id to be added\&. 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error (node already exists or outside the bounds of the implementation); otherwise, 1 if successful\&.
.RE
.PP
Remove the given node from the list, and repair the linkages appropriately\&.
.PP
\fBParameters\fP
.RS 4
\fInodeid\fP Node id to be added\&. 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error (node already exists or outside the bounds of the implementation); otherwise, 1 if successful\&. 
.RE
.PP

.SS "int linkResetGraph (struct \fBgraph_t\fP * g, void * args, void(*)(void) callback)"

.PP
Function pointer to 'reset' the graph according to the given argument pointer\&. For some implementations, it is more efficient to reuse the existing graph structure and perform a 'zero-out' of the data, rather than rebuilding from scratch\&. This function pointer provides that option\&. 
.PP
\fBParameters\fP
.RS 4
\fIg\fP Graph structure to be zeroed or modified according to reset logic 
.br
\fIargs\fP Arguments to be used in the reset process, if necessary 
.br
\fIcallback\fP Callback to be executed when graph has been reset\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error during the reset; 1 if the reset completed;
.RE
.PP
Walk the edges and set capacities and flows to zero\&.
.PP
\fBParameters\fP
.RS 4
\fIg\fP Graph structure to be zeroed or modified according to reset logic 
.br
\fIargs\fP Arguments to be used in the reset process, if necessary 
.br
\fIcallback\fP Callback to be executed when graph has been reset\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error during the reset; 1 if the reset completed; 
.RE
.PP

.SS "int linkSetCapacity (const size_t * uid, const size_t * vid, const double * cap, struct \fBgraph_t\fP * g)"

.PP
Function pointer to set the capacity (cost, weight, etc\&.) of an edge in the given graph\&. 
.PP
\fBParameters\fP
.RS 4
\fIuid\fP identifier of the edge start 
.br
\fIvid\fP identifier of the edge ending\&. 
.br
\fIcap\fP capacity value to be set 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 if there was an error; 1 if the capacity was successfully set 
.RE
.PP

.SS "int linkSetFlow (const size_t * uid, const size_t * vid, const double * flow, struct \fBgraph_t\fP * g)"

.PP
Function to set the flow value for an edge (amount of capacity currently 'used') For implementations that require it, this allows tracking of flow values that are used within the graph\&.
.PP
\fBParameters\fP
.RS 4
\fIuid\fP Identifier of the edge start\&. 
.br
\fIvid\fP Identifier of the edge end\&. 
.br
\fIflow\fP Value to be set for the flow\&. 
.br
\fIg\fP Graph structure in question 
.RE
.PP
\fBReturns\fP
.RS 4
0 of there was an error (edge not found, for example); otherwise, 1 if the flow value as successfully set\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
