.TH "node_t" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_t \- Graph node structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphData\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnodeid\fP"
.br
.ti -1c
.RI "struct \fBfeature_t\fP * \fBattrs\fP"
.br
.ti -1c
.RI "struct \fBedge_t\fP * \fBedges\fP"
.br
.ti -1c
.RI "struct \fBnode_t\fP * \fBprev\fP"
.br
.RI "Previous node, as required\&. Typical usage would be in node-based path list\&. "
.ti -1c
.RI "struct \fBnode_t\fP * \fBnext\fP"
.br
.RI "Next node, as required\&. Typical usage would be in node-based path list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Graph node structure\&. 

This structure represents individual graph nodes and associated structures\&. Actual usage of the structure associations is up to the individual implementations\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBfeature_t\fP* node_t::attrs"
Attached features, if any\&. Initialized as NULL for all implementations\&. 
.SS "struct \fBedge_t\fP* node_t::edges"
Attached edges, if any\&. 
.SS "struct \fBnode_t\fP* node_t::next"

.PP
Next node, as required\&. Typical usage would be in node-based path list\&. 
.SS "size_t node_t::nodeid"
Node identifier 
.SS "struct \fBnode_t\fP* node_t::prev"

.PP
Previous node, as required\&. Typical usage would be in node-based path list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
