.TH "/devel/graphdata/graphDataLib/include/impl/sharedmemgraph.h" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/devel/graphdata/graphDataLib/include/impl/sharedmemgraph.h
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
