.TH "/devel/graphdata/graphDataLib/src/impl/sharedmmapgraph.c" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/devel/graphdata/graphDataLib/src/impl/sharedmmapgraph.c
.SH SYNOPSIS
.br
.PP
\fC#include <impl/sharedmmapgraph\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
