.TH "/devel/graphdata/graphDataLib/src/impl/sharedmmapops.c" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/devel/graphdata/graphDataLib/src/impl/sharedmmapops.c
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
