.TH "/devel/graphdata/graphDataLib/src/impl/sharedmemops.c" 3 "Graph Data Shared Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/devel/graphdata/graphDataLib/src/impl/sharedmemops.c
.SH SYNOPSIS
.br
.PP
\fC#include <impl/sharedmemops\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Graph Data Shared Library from the source code\&.
